#@data/values
---
name: dev-briq-builder
env: test
static_ip: lb-sltech-company-ipv4-4
sites: ["test.sltech.company"]
#@schema/type any=True
defaultLabels:
  appname: dev-briq
  env: test
#! Temporarily secure the test site.
useSecurity: true
resources:
  node:
    cpu: "50m"
    memory: "128Mi"
  nginx:
    cpu: "50m"
    memory: "128Mi"
