#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ data.values.name
  labels: #@ data.values.defaultLabels
spec:
  replicas: 1
  selector:
    matchLabels: #@ data.values.defaultLabels
  template:
    metadata:
      labels: #@ data.values.defaultLabels
    spec:
      containers:
      - name: #@ data.values.name
        image: #@ "europe-west3-docker.pkg.dev/healthy-saga-329513/sltech-briq/" + data.values.image_name + ":" + data.values.image_tag
        ports:
        - containerPort: 80
        volumeMounts:
#@ if data.values.useSecurity:
        - name: password
          mountPath: "/etc/nginx/secrets/"
#@ end
        - name: nginx-conf
          mountPath: /etc/nginx/security
        resources:
          requests:
            cpu: #@ data.values.resources.nginx.cpu
            memory: #@ data.values.resources.nginx.memory 
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 2
      - name: #@ data.values.name + "-node"
        image: #@ "europe-west3-docker.pkg.dev/healthy-saga-329513/sltech-briq/" + data.values.image_name + "-node:" + data.values.image_tag
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: #@ data.values.resources.node.cpu
            memory: #@ data.values.resources.node.memory
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 2
      volumes:
      - name: password
        secret:
          secretName: adminpassword
      - name: nginx-conf
        configMap:
          name: #@ data.values.name + "-secu"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: #@ data.values.name + "-secu"
  labels: #@ data.values.defaultLabels
data:
#@ if data.values.useSecurity:
  security.conf: |
    auth_basic "admin protection";
    auth_basic_user_file /etc/nginx/secrets/password;

    # Relay for the API to hide the testnet API if you're no authenticated.
    location /api_relay/ {
        proxy_set_header   X-Forwarded-For $remote_addr;
        proxy_set_header   Host $http_host;
        proxy_pass         http://dev-briq-protocol.default.svc.cluster.local/;
    }

#@ else:
  security.conf: |
    auth_basic off;
#@ end
