#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Service
metadata:
  name: #@ data.values.name
  labels: #@ data.values.defaultLabels
  annotations:
    cloud.google.com/backend-config: #@ '{"default": "' + data.values.name + '"}'
spec:
  selector:
    appname: #@ data.values.name
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: #@ data.values.name
  labels: #@ data.values.defaultLabels
spec:
  timeoutSec: 10
  healthCheck:
    checkIntervalSec: 100
    timeoutSec: 10
    port: 8080
    type: HTTP
    requestPath: /health
