name: deploy
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: SSH to VM & deploy.
        run: gcloud compute ssh ${{ secrets.GCP_INSTANCE }} --zone="europe-west3-c" --ssh-key-expire-after=2m --command="git clone https://github.com/S-L-Technologies/brq-builder.git"
