name: run_tests
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  deploy:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm ci --include=dev
    - run: npm test
